#!/usr/bin/env python3
"""Extract reviewed XGK model restrictions from local InstructionHelp V3.5.

Only unambiguous chapter 4.39/4.40 model tables and INLATCH are covered.
Unknown commands/models remain unknown; firmware and module requirements are
not inferred from database bit masks or from these model tables.
"""
import argparse
from html.parser import HTMLParser
from pathlib import Path
import re
import subprocess

class Tables(HTMLParser):
    def __init__(self):
        super().__init__(); self.tables = []; self.rows = self.cells = self.cell = None
    def handle_starttag(self, tag, attrs):
        if tag == 'table': self.rows = []
        elif tag == 'tr': self.cells = []
        elif tag in ('td', 'th'): self.cell = []
    def handle_data(self, data):
        if self.cell is not None: self.cell.append(data)
    def handle_endtag(self, tag):
        if tag in ('td', 'th') and self.cell is not None:
            if self.cells is not None: self.cells.append(' '.join(''.join(self.cell).split()))
            self.cell = None
        elif tag == 'tr' and self.rows is not None:
            self.rows.append(self.cells or []); self.cells = None
        elif tag == 'table' and self.rows is not None:
            self.tables.append(self.rows); self.rows = None

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('manual', type=Path)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
catalog = set(re.findall(r'mnemonic: "([^"]+)"', (root/'src/instruction_catalog.rs').read_text()))
models = ['U', 'H', 'A', 'S', 'E', 'UN', 'HN', 'SN']
rules = {}
for path in sorted(args.manual.glob('*.htm')):
    if not path.name.startswith(('439', '440')): continue
    html = path.read_bytes().decode('cp949')
    tables = Tables(); tables.feed(html)
    title = re.search(r'<title>(.*?)</title>', html, re.S)
    if not title: continue
    names = set(re.findall(r'[A-Z][A-Z0-9_]*', title[1])) & catalog
    for table in tables.tables:
        if not table or table[0][:3] != ['지원 기종', 'XGK', 'XGK-N']: continue
        assert len(table) == 3 and table[1][:8] == models, path.name
        permissions = table[2][:8]
        assert len(permissions) == 8 and set(permissions) <= {'O', 'X', '-'}, path.name
        allowed = [m for m, v in zip(models, permissions) if v == 'O']
        for name in names:
            entry = (path.name, allowed)
            if name in rules and rules[name][1] != allowed:
                raise ValueError('Conflicting model tables: '+name)
            rules.setdefault(name, entry)
# This page states the three models explicitly in the explanation.
page = args.manual/'42421inlatch.htm'
html = page.read_bytes().decode('cp949')
assert all('XGK-CPU'+m in html for m in ['UN', 'HN', 'SN'])
rules['INLATCH'] = (page.name, ['UN', 'HN', 'SN'])
assert len(rules) >= 25, 'Missing reviewed model tables'
out = '''//! Factual model tables from InstructionHelp_Kr_V3.5; no manual prose.
//! Generated by scripts/generate-instruction-availability.py.
use super::LadderInstructionCpuRestriction;
pub(super) fn restriction(name: &str) -> Option<LadderInstructionCpuRestriction> {
    match name {
'''
for name, (page, allowed) in sorted(rules.items()):
    models_text = ', '.join('"XGK-CPU'+m+'"' for m in allowed)
    out += f'        "{name}" => Some(LadderInstructionCpuRestriction {{ models: &[{models_text}], manual_page: "{page}" }}),\n'
out += '        _ => None,\n    }\n}\n'
out = subprocess.run(['rustfmt', '--edition', '2024'], input=out, text=True, capture_output=True, check=True).stdout
path = root/'src/instruction_cpu_data.rs'
if args.check:
    if path.read_text() != out: raise SystemExit('Instruction CPU data is stale')
else: path.write_text(out)
print(f'{len(rules)} instructions with reviewed XGK model tables')
