#!/usr/bin/env python3
"""Generate LOAD comparison identifiers from a private native XGTCodeDB TSV.

The ladder editor expresses AND/OR through its existing series/branch wiring;
each comparison cell uses the native LOAD-family record identifier.
"""
import csv
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parents[1]
with Path(sys.argv[1]).open(encoding='utf-8') as stream:
    assert next(stream).strip() == 'XGTCodeDB'
    rows = {r['Command'].strip(): r for r in csv.DictReader(stream, delimiter='\t')}
families = [('', ''), ('D', ''), ('R', ''), ('L', ''), ('$', ''),
            ('G', ''), ('DG', ''), ('', '3'), ('D', '3'),
            ('4', ''), ('8', ''), ('U', ''), ('UD', '')]
text = '''//! Native XGK input comparisons from XGTCodeDB.
//! Generated by scripts/generate-comparison-catalog.py.
use crate::instruction_catalog::LadderInstructionSpec;

/// Comparison contacts use the instruction envelope with contact flags.
pub fn ladder_comparison_catalog() -> &'static [LadderInstructionSpec] {
    &[
'''
for prefix, suffix in families:
    for relation in ['=', '>', '<', '>=', '<=', '<>']:
        name = prefix + relation + suffix
        row = rows['LOAD' + name]
        assert row['byCmdList'] == '6' and row['strShowList'].endswith('10')
        assert int(row['bySize']) == (3 if prefix in ['G', 'DG'] or suffix else 2)
        text += f'        LadderInstructionSpec {{ mnemonic: "{name}", opcode: {int(row["nIndex"])}, operand_count: {int(row["bySize"])} }},\n'
text += '    ]\n}\n'
for mnemonic, native_name in [('B', 'LOADB'), ('BN', 'LOADBN')]:
    row = rows[native_name]
    assert row['byCmdList'] == '32' and row['strShowList'].endswith('10') and int(row['bySize']) == 2
    entry = f'        LadderInstructionSpec {{ mnemonic: "{mnemonic}", opcode: {int(row["nIndex"])}, operand_count: 2 }},\n'
    text = text.replace('    ]\n}\n', entry + '    ]\n}\n')
formatted = subprocess.run(['rustfmt', '--edition', '2024'], input=text,
                           text=True, capture_output=True, check=True).stdout
(root/'src/comparison_catalog.rs').write_text(formatted)
print('78 comparisons and 2 indexed-bit contacts; native IDs and arities verified against the database')
