#!/usr/bin/env python3
"""Generate factual LD instruction IDs from a tab-separated XGTCodeDB export.

Usage: python3 scripts/generate-instruction-catalog.py /path/to/XGTCodeDB.tsv
The first line is the table name, followed by a tab-separated header and rows.
The proprietary source database is not distributed with this project.
"""
import csv
import hashlib
from pathlib import Path
import sys

source = Path(sys.argv[1])
with source.open(encoding="utf-8") as stream:
    assert next(stream).strip() == "XGTCodeDB"
    rows = list(csv.DictReader(stream, delimiter="\t"))
# LD-visible, fixed-arity application blocks. Exclude basic/control-flow
# categories whose native record layouts need separate structural support.
# BRST/BRSTP and FF are native-captured exceptions using the application envelope.
rows = sorted((r for r in rows if r["strShowList"].endswith("11")
               and 0 <= int(r["bySize"]) <= 8
               and (r["byCmdList"] not in {"1", "22", "1000"}
                    or r["Command"].strip() in {"BRST", "BRSTP", "FF"})),
              key=lambda r: r["Command"].strip())
assert len({r["Command"].strip() for r in rows}) == len(rows)
text = '''//! Fixed-arity application-instruction identifiers from XG5000 XGTCodeDB.
//! Generated by scripts/generate-instruction-catalog.py; see docs/ladder-editing.md.
#[derive(Debug, Clone, Copy)]
#[cfg_attr(feature = "wasm", derive(serde::Serialize))]
#[cfg_attr(feature = "wasm", serde(rename_all = "camelCase"))]
pub struct LadderInstructionSpec {
    pub mnemonic: &'static str,
    pub opcode: u32,
    pub operand_count: usize,
}

pub fn ladder_instruction_catalog() -> &'static [LadderInstructionSpec] {
    &[
'''
for row in rows:
    name = row["Command"].strip()
    assert name.isascii() and all(c.isalnum() or c in '$ _><=+-*/' for c in name), name
    text += f'        LadderInstructionSpec {{ mnemonic: "{name}", opcode: {int(row["nIndex"])}, operand_count: {int(row["bySize"])} }},\n'
text += '    ]\n}\n'
Path('src/instruction_catalog.rs').write_text(text)
print(f'{len(rows)} instructions; source SHA-256 {hashlib.sha256(source.read_bytes()).hexdigest()}')
