//! Native XGK input comparisons from XGTCodeDB.
//! Generated by scripts/generate-comparison-catalog.py.
use crate::instruction_catalog::LadderInstructionSpec;

/// Comparison contacts use the instruction envelope with contact flags.
pub fn ladder_comparison_catalog() -> &'static [LadderInstructionSpec] {
    &[
        LadderInstructionSpec {
            mnemonic: "=",
            opcode: 1254,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: ">",
            opcode: 1256,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "<",
            opcode: 1258,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: ">=",
            opcode: 1260,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "<=",
            opcode: 1262,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "<>",
            opcode: 1264,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "D=",
            opcode: 1255,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "D>",
            opcode: 1257,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "D<",
            opcode: 1259,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "D>=",
            opcode: 1261,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "D<=",
            opcode: 1263,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "D<>",
            opcode: 1265,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "R=",
            opcode: 1290,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "R>",
            opcode: 1292,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "R<",
            opcode: 1294,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "R>=",
            opcode: 1296,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "R<=",
            opcode: 1298,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "R<>",
            opcode: 1300,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "L=",
            opcode: 1291,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "L>",
            opcode: 1293,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "L<",
            opcode: 1295,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "L>=",
            opcode: 1297,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "L<=",
            opcode: 1299,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "L<>",
            opcode: 1301,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "$=",
            opcode: 1398,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "$>",
            opcode: 1399,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "$<",
            opcode: 1400,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "$>=",
            opcode: 1401,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "$<=",
            opcode: 1402,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "$<>",
            opcode: 1403,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "G=",
            opcode: 1326,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "G>",
            opcode: 1327,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "G<",
            opcode: 1328,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "G>=",
            opcode: 1329,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "G<=",
            opcode: 1330,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "G<>",
            opcode: 1331,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "DG=",
            opcode: 1332,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "DG>",
            opcode: 1333,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "DG<",
            opcode: 1334,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "DG>=",
            opcode: 1335,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "DG<=",
            opcode: 1336,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "DG<>",
            opcode: 1337,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "=3",
            opcode: 1362,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: ">3",
            opcode: 1364,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "<3",
            opcode: 1366,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: ">=3",
            opcode: 1368,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "<=3",
            opcode: 1370,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "<>3",
            opcode: 1372,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "D=3",
            opcode: 1363,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "D>3",
            opcode: 1365,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "D<3",
            opcode: 1367,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "D>=3",
            opcode: 1369,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "D<=3",
            opcode: 1371,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "D<>3",
            opcode: 1373,
            operand_count: 3,
        },
        LadderInstructionSpec {
            mnemonic: "4=",
            opcode: 1416,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "4>",
            opcode: 1418,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "4<",
            opcode: 1420,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "4>=",
            opcode: 1422,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "4<=",
            opcode: 1424,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "4<>",
            opcode: 1426,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "8=",
            opcode: 1417,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "8>",
            opcode: 1419,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "8<",
            opcode: 1421,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "8>=",
            opcode: 1423,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "8<=",
            opcode: 1425,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "8<>",
            opcode: 1427,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "U=",
            opcode: 1491,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "U>",
            opcode: 1492,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "U<",
            opcode: 1493,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "U>=",
            opcode: 1494,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "U<=",
            opcode: 1495,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "U<>",
            opcode: 1496,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "UD=",
            opcode: 1509,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "UD>",
            opcode: 1510,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "UD<",
            opcode: 1511,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "UD>=",
            opcode: 1512,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "UD<=",
            opcode: 1513,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "UD<>",
            opcode: 1514,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "B",
            opcode: 1065,
            operand_count: 2,
        },
        LadderInstructionSpec {
            mnemonic: "BN",
            opcode: 1066,
            operand_count: 2,
        },
    ]
}
