//! Factual model tables from InstructionHelp_Kr_V3.5; no manual prose.
//! Generated by scripts/generate-instruction-availability.py.
use super::LadderInstructionCpuRestriction;
pub(super) fn restriction(name: &str) -> Option<LadderInstructionCpuRestriction> {
    match name {
        "CPMSG" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44023cp_msg.htm",
        }),
        "FCS" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44018fcs.htm",
        }),
        "GET" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4391getgetp.htm",
        }),
        "GETCOMM" => Some(LadderInstructionCpuRestriction {
            models: &[],
            manual_page: "44016getcomm.htm",
        }),
        "GETE" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4392getegetepxgf-rd8a.htm",
        }),
        "GETEP" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4392getegetepxgf-rd8a.htm",
        }),
        "GETIP" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44010getip.htm",
        }),
        "GETP" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4391getgetp.htm",
        }),
        "GETPARAM" => Some(LadderInstructionCpuRestriction {
            models: &[],
            manual_page: "44022getparam.htm",
        }),
        "GETPORT" => Some(LadderInstructionCpuRestriction {
            models: &[],
            manual_page: "44020getport.htm",
        }),
        "INLATCH" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "42421inlatch.htm",
        }),
        "LNETINFO" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44014lnetinfo.htm",
        }),
        "MGETLED" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44015mgetled.htm",
        }),
        "MNETINFO" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44012mnetinfo.htm",
        }),
        "MSETDNETS" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44023cp_msg2.htm",
        }),
        "MSETIP" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44013msetip.htm",
        }),
        "P2PBRD" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4404p2pbrdbit.htm",
        }),
        "P2PBWR" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4405p2pbwrbit.htm",
        }),
        "P2PSN" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4401p2psn.htm",
        }),
        "P2PWRD" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4402p2pwrd.htm",
        }),
        "P2PWWR" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4403p2pwwrword.htm",
        }),
        "PUT" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4393putputp.htm",
        }),
        "PUTCOMM" => Some(LadderInstructionCpuRestriction {
            models: &[],
            manual_page: "44017putcomm.htm",
        }),
        "PUTP" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4393putputp.htm",
        }),
        "RCVUDATA" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4407rcvudata.htm",
        }),
        "SENDDTR" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4408senddtr.htm",
        }),
        "SENDRTS" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4409sendrts.htm",
        }),
        "SETIP" => Some(LadderInstructionCpuRestriction {
            models: &["XGK-CPUUN", "XGK-CPUHN", "XGK-CPUSN"],
            manual_page: "44011setip.htm",
        }),
        "SETPARAM" => Some(LadderInstructionCpuRestriction {
            models: &[],
            manual_page: "44021setparam.htm",
        }),
        "SETPORT" => Some(LadderInstructionCpuRestriction {
            models: &[],
            manual_page: "44019setport.htm",
        }),
        "SNDUDATA" => Some(LadderInstructionCpuRestriction {
            models: &[
                "XGK-CPUU",
                "XGK-CPUH",
                "XGK-CPUA",
                "XGK-CPUS",
                "XGK-CPUE",
                "XGK-CPUUN",
                "XGK-CPUHN",
                "XGK-CPUSN",
            ],
            manual_page: "4406sndudata.htm",
        }),
        _ => None,
    }
}
