// Digital I/O symbols observed in native fixtures/elements-io.xgwx.
// Regenerate only from reviewed native captures. Source order is preserved.
use super::{IoSpec, IoTemplate};
pub(super) const SPECS: &[IoSpec] = &[
    IoSpec {
        id: 42240,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
        ],
    },
    IoSpec {
        id: 42241,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
            IoTemplate {
                suffix: "IN08",
                bit: 8,
                direction: "IN",
                description: "입력 접점 08",
            },
            IoTemplate {
                suffix: "IN09",
                bit: 9,
                direction: "IN",
                description: "입력 접점 09",
            },
            IoTemplate {
                suffix: "IN10",
                bit: 10,
                direction: "IN",
                description: "입력 접점 10",
            },
            IoTemplate {
                suffix: "IN11",
                bit: 11,
                direction: "IN",
                description: "입력 접점 11",
            },
            IoTemplate {
                suffix: "IN12",
                bit: 12,
                direction: "IN",
                description: "입력 접점 12",
            },
            IoTemplate {
                suffix: "IN13",
                bit: 13,
                direction: "IN",
                description: "입력 접점 13",
            },
            IoTemplate {
                suffix: "IN14",
                bit: 14,
                direction: "IN",
                description: "입력 접점 14",
            },
            IoTemplate {
                suffix: "IN15",
                bit: 15,
                direction: "IN",
                description: "입력 접점 15",
            },
        ],
    },
    IoSpec {
        id: 42242,
        points: 32,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
            IoTemplate {
                suffix: "IN08",
                bit: 8,
                direction: "IN",
                description: "입력 접점 08",
            },
            IoTemplate {
                suffix: "IN09",
                bit: 9,
                direction: "IN",
                description: "입력 접점 09",
            },
            IoTemplate {
                suffix: "IN10",
                bit: 10,
                direction: "IN",
                description: "입력 접점 10",
            },
            IoTemplate {
                suffix: "IN11",
                bit: 11,
                direction: "IN",
                description: "입력 접점 11",
            },
            IoTemplate {
                suffix: "IN12",
                bit: 12,
                direction: "IN",
                description: "입력 접점 12",
            },
            IoTemplate {
                suffix: "IN13",
                bit: 13,
                direction: "IN",
                description: "입력 접점 13",
            },
            IoTemplate {
                suffix: "IN14",
                bit: 14,
                direction: "IN",
                description: "입력 접점 14",
            },
            IoTemplate {
                suffix: "IN15",
                bit: 15,
                direction: "IN",
                description: "입력 접점 15",
            },
            IoTemplate {
                suffix: "IN16",
                bit: 16,
                direction: "IN",
                description: "입력 접점 16",
            },
            IoTemplate {
                suffix: "IN17",
                bit: 17,
                direction: "IN",
                description: "입력 접점 17",
            },
            IoTemplate {
                suffix: "IN18",
                bit: 18,
                direction: "IN",
                description: "입력 접점 18",
            },
            IoTemplate {
                suffix: "IN19",
                bit: 19,
                direction: "IN",
                description: "입력 접점 19",
            },
            IoTemplate {
                suffix: "IN20",
                bit: 20,
                direction: "IN",
                description: "입력 접점 20",
            },
            IoTemplate {
                suffix: "IN21",
                bit: 21,
                direction: "IN",
                description: "입력 접점 21",
            },
            IoTemplate {
                suffix: "IN22",
                bit: 22,
                direction: "IN",
                description: "입력 접점 22",
            },
            IoTemplate {
                suffix: "IN23",
                bit: 23,
                direction: "IN",
                description: "입력 접점 23",
            },
            IoTemplate {
                suffix: "IN24",
                bit: 24,
                direction: "IN",
                description: "입력 접점 24",
            },
            IoTemplate {
                suffix: "IN25",
                bit: 25,
                direction: "IN",
                description: "입력 접점 25",
            },
            IoTemplate {
                suffix: "IN26",
                bit: 26,
                direction: "IN",
                description: "입력 접점 26",
            },
            IoTemplate {
                suffix: "IN27",
                bit: 27,
                direction: "IN",
                description: "입력 접점 27",
            },
            IoTemplate {
                suffix: "IN28",
                bit: 28,
                direction: "IN",
                description: "입력 접점 28",
            },
            IoTemplate {
                suffix: "IN29",
                bit: 29,
                direction: "IN",
                description: "입력 접점 29",
            },
            IoTemplate {
                suffix: "IN30",
                bit: 30,
                direction: "IN",
                description: "입력 접점 30",
            },
            IoTemplate {
                suffix: "IN31",
                bit: 31,
                direction: "IN",
                description: "입력 접점 31",
            },
        ],
    },
    IoSpec {
        id: 42243,
        points: 64,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
            IoTemplate {
                suffix: "IN08",
                bit: 8,
                direction: "IN",
                description: "입력 접점 08",
            },
            IoTemplate {
                suffix: "IN09",
                bit: 9,
                direction: "IN",
                description: "입력 접점 09",
            },
            IoTemplate {
                suffix: "IN10",
                bit: 10,
                direction: "IN",
                description: "입력 접점 10",
            },
            IoTemplate {
                suffix: "IN11",
                bit: 11,
                direction: "IN",
                description: "입력 접점 11",
            },
            IoTemplate {
                suffix: "IN12",
                bit: 12,
                direction: "IN",
                description: "입력 접점 12",
            },
            IoTemplate {
                suffix: "IN13",
                bit: 13,
                direction: "IN",
                description: "입력 접점 13",
            },
            IoTemplate {
                suffix: "IN14",
                bit: 14,
                direction: "IN",
                description: "입력 접점 14",
            },
            IoTemplate {
                suffix: "IN15",
                bit: 15,
                direction: "IN",
                description: "입력 접점 15",
            },
            IoTemplate {
                suffix: "IN16",
                bit: 16,
                direction: "IN",
                description: "입력 접점 16",
            },
            IoTemplate {
                suffix: "IN17",
                bit: 17,
                direction: "IN",
                description: "입력 접점 17",
            },
            IoTemplate {
                suffix: "IN18",
                bit: 18,
                direction: "IN",
                description: "입력 접점 18",
            },
            IoTemplate {
                suffix: "IN19",
                bit: 19,
                direction: "IN",
                description: "입력 접점 19",
            },
            IoTemplate {
                suffix: "IN20",
                bit: 20,
                direction: "IN",
                description: "입력 접점 20",
            },
            IoTemplate {
                suffix: "IN21",
                bit: 21,
                direction: "IN",
                description: "입력 접점 21",
            },
            IoTemplate {
                suffix: "IN22",
                bit: 22,
                direction: "IN",
                description: "입력 접점 22",
            },
            IoTemplate {
                suffix: "IN23",
                bit: 23,
                direction: "IN",
                description: "입력 접점 23",
            },
            IoTemplate {
                suffix: "IN24",
                bit: 24,
                direction: "IN",
                description: "입력 접점 24",
            },
            IoTemplate {
                suffix: "IN25",
                bit: 25,
                direction: "IN",
                description: "입력 접점 25",
            },
            IoTemplate {
                suffix: "IN26",
                bit: 26,
                direction: "IN",
                description: "입력 접점 26",
            },
            IoTemplate {
                suffix: "IN27",
                bit: 27,
                direction: "IN",
                description: "입력 접점 27",
            },
            IoTemplate {
                suffix: "IN28",
                bit: 28,
                direction: "IN",
                description: "입력 접점 28",
            },
            IoTemplate {
                suffix: "IN29",
                bit: 29,
                direction: "IN",
                description: "입력 접점 29",
            },
            IoTemplate {
                suffix: "IN30",
                bit: 30,
                direction: "IN",
                description: "입력 접점 30",
            },
            IoTemplate {
                suffix: "IN31",
                bit: 31,
                direction: "IN",
                description: "입력 접점 31",
            },
            IoTemplate {
                suffix: "IN32",
                bit: 32,
                direction: "IN",
                description: "입력 접점 32",
            },
            IoTemplate {
                suffix: "IN33",
                bit: 33,
                direction: "IN",
                description: "입력 접점 33",
            },
            IoTemplate {
                suffix: "IN34",
                bit: 34,
                direction: "IN",
                description: "입력 접점 34",
            },
            IoTemplate {
                suffix: "IN35",
                bit: 35,
                direction: "IN",
                description: "입력 접점 35",
            },
            IoTemplate {
                suffix: "IN36",
                bit: 36,
                direction: "IN",
                description: "입력 접점 36",
            },
            IoTemplate {
                suffix: "IN37",
                bit: 37,
                direction: "IN",
                description: "입력 접점 37",
            },
            IoTemplate {
                suffix: "IN38",
                bit: 38,
                direction: "IN",
                description: "입력 접점 38",
            },
            IoTemplate {
                suffix: "IN39",
                bit: 39,
                direction: "IN",
                description: "입력 접점 39",
            },
            IoTemplate {
                suffix: "IN40",
                bit: 40,
                direction: "IN",
                description: "입력 접점 40",
            },
            IoTemplate {
                suffix: "IN41",
                bit: 41,
                direction: "IN",
                description: "입력 접점 41",
            },
            IoTemplate {
                suffix: "IN42",
                bit: 42,
                direction: "IN",
                description: "입력 접점 42",
            },
            IoTemplate {
                suffix: "IN43",
                bit: 43,
                direction: "IN",
                description: "입력 접점 43",
            },
            IoTemplate {
                suffix: "IN44",
                bit: 44,
                direction: "IN",
                description: "입력 접점 44",
            },
            IoTemplate {
                suffix: "IN45",
                bit: 45,
                direction: "IN",
                description: "입력 접점 45",
            },
            IoTemplate {
                suffix: "IN46",
                bit: 46,
                direction: "IN",
                description: "입력 접점 46",
            },
            IoTemplate {
                suffix: "IN47",
                bit: 47,
                direction: "IN",
                description: "입력 접점 47",
            },
            IoTemplate {
                suffix: "IN48",
                bit: 48,
                direction: "IN",
                description: "입력 접점 48",
            },
            IoTemplate {
                suffix: "IN49",
                bit: 49,
                direction: "IN",
                description: "입력 접점 49",
            },
            IoTemplate {
                suffix: "IN50",
                bit: 50,
                direction: "IN",
                description: "입력 접점 50",
            },
            IoTemplate {
                suffix: "IN51",
                bit: 51,
                direction: "IN",
                description: "입력 접점 51",
            },
            IoTemplate {
                suffix: "IN52",
                bit: 52,
                direction: "IN",
                description: "입력 접점 52",
            },
            IoTemplate {
                suffix: "IN53",
                bit: 53,
                direction: "IN",
                description: "입력 접점 53",
            },
            IoTemplate {
                suffix: "IN54",
                bit: 54,
                direction: "IN",
                description: "입력 접점 54",
            },
            IoTemplate {
                suffix: "IN55",
                bit: 55,
                direction: "IN",
                description: "입력 접점 55",
            },
            IoTemplate {
                suffix: "IN56",
                bit: 56,
                direction: "IN",
                description: "입력 접점 56",
            },
            IoTemplate {
                suffix: "IN57",
                bit: 57,
                direction: "IN",
                description: "입력 접점 57",
            },
            IoTemplate {
                suffix: "IN58",
                bit: 58,
                direction: "IN",
                description: "입력 접점 58",
            },
            IoTemplate {
                suffix: "IN59",
                bit: 59,
                direction: "IN",
                description: "입력 접점 59",
            },
            IoTemplate {
                suffix: "IN60",
                bit: 60,
                direction: "IN",
                description: "입력 접점 60",
            },
            IoTemplate {
                suffix: "IN61",
                bit: 61,
                direction: "IN",
                description: "입력 접점 61",
            },
            IoTemplate {
                suffix: "IN62",
                bit: 62,
                direction: "IN",
                description: "입력 접점 62",
            },
            IoTemplate {
                suffix: "IN63",
                bit: 63,
                direction: "IN",
                description: "입력 접점 63",
            },
        ],
    },
    IoSpec {
        id: 42385,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
            IoTemplate {
                suffix: "IN08",
                bit: 8,
                direction: "IN",
                description: "입력 접점 08",
            },
            IoTemplate {
                suffix: "IN09",
                bit: 9,
                direction: "IN",
                description: "입력 접점 09",
            },
            IoTemplate {
                suffix: "IN10",
                bit: 10,
                direction: "IN",
                description: "입력 접점 10",
            },
            IoTemplate {
                suffix: "IN11",
                bit: 11,
                direction: "IN",
                description: "입력 접점 11",
            },
            IoTemplate {
                suffix: "IN12",
                bit: 12,
                direction: "IN",
                description: "입력 접점 12",
            },
            IoTemplate {
                suffix: "IN13",
                bit: 13,
                direction: "IN",
                description: "입력 접점 13",
            },
            IoTemplate {
                suffix: "IN14",
                bit: 14,
                direction: "IN",
                description: "입력 접점 14",
            },
            IoTemplate {
                suffix: "IN15",
                bit: 15,
                direction: "IN",
                description: "입력 접점 15",
            },
        ],
    },
    IoSpec {
        id: 42368,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
        ],
    },
    IoSpec {
        id: 42353,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "CH0_DIAG",
                bit: 8,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 0 단선 진단",
            },
            IoTemplate {
                suffix: "CH0_IN",
                bit: 0,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 0",
            },
            IoTemplate {
                suffix: "CH1_DIAG",
                bit: 9,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 1 단선 진단",
            },
            IoTemplate {
                suffix: "CH1_IN",
                bit: 1,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 1",
            },
            IoTemplate {
                suffix: "CH2_DIAG",
                bit: 10,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 2 단선 진단",
            },
            IoTemplate {
                suffix: "CH2_IN",
                bit: 2,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 2",
            },
            IoTemplate {
                suffix: "CH3_DIAG",
                bit: 11,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 3 단선 진단",
            },
            IoTemplate {
                suffix: "CH3_IN",
                bit: 3,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 3",
            },
            IoTemplate {
                suffix: "CH4_DIAG",
                bit: 12,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 4 단선 진단",
            },
            IoTemplate {
                suffix: "CH4_IN",
                bit: 4,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 4",
            },
            IoTemplate {
                suffix: "CH5_DIAG",
                bit: 13,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 5 단선 진단",
            },
            IoTemplate {
                suffix: "CH5_IN",
                bit: 5,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 5",
            },
            IoTemplate {
                suffix: "CH6_DIAG",
                bit: 14,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 6 단선 진단",
            },
            IoTemplate {
                suffix: "CH6_IN",
                bit: 6,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 6",
            },
            IoTemplate {
                suffix: "CH7_DIAG",
                bit: 15,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 7 단선 진단",
            },
            IoTemplate {
                suffix: "CH7_IN",
                bit: 7,
                direction: "IN",
                description: "진단형 DC 입력 모듈: 입력 신호 7",
            },
        ],
    },
    IoSpec {
        id: 42282,
        points: 32,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
            IoTemplate {
                suffix: "IN06",
                bit: 6,
                direction: "IN",
                description: "입력 접점 06",
            },
            IoTemplate {
                suffix: "IN07",
                bit: 7,
                direction: "IN",
                description: "입력 접점 07",
            },
            IoTemplate {
                suffix: "IN08",
                bit: 8,
                direction: "IN",
                description: "입력 접점 08",
            },
            IoTemplate {
                suffix: "IN09",
                bit: 9,
                direction: "IN",
                description: "입력 접점 09",
            },
            IoTemplate {
                suffix: "IN10",
                bit: 10,
                direction: "IN",
                description: "입력 접점 10",
            },
            IoTemplate {
                suffix: "IN11",
                bit: 11,
                direction: "IN",
                description: "입력 접점 11",
            },
            IoTemplate {
                suffix: "IN12",
                bit: 12,
                direction: "IN",
                description: "입력 접점 12",
            },
            IoTemplate {
                suffix: "IN13",
                bit: 13,
                direction: "IN",
                description: "입력 접점 13",
            },
            IoTemplate {
                suffix: "IN14",
                bit: 14,
                direction: "IN",
                description: "입력 접점 14",
            },
            IoTemplate {
                suffix: "IN15",
                bit: 15,
                direction: "IN",
                description: "입력 접점 15",
            },
            IoTemplate {
                suffix: "OUT00",
                bit: 16,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 17,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 18,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 19,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 20,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 21,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 22,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 23,
                direction: "OUT",
                description: "출력 접점 07",
            },
            IoTemplate {
                suffix: "OUT08",
                bit: 24,
                direction: "OUT",
                description: "출력 접점 08",
            },
            IoTemplate {
                suffix: "OUT09",
                bit: 25,
                direction: "OUT",
                description: "출력 접점 09",
            },
            IoTemplate {
                suffix: "OUT10",
                bit: 26,
                direction: "OUT",
                description: "출력 접점 10",
            },
            IoTemplate {
                suffix: "OUT11",
                bit: 27,
                direction: "OUT",
                description: "출력 접점 11",
            },
            IoTemplate {
                suffix: "OUT12",
                bit: 28,
                direction: "OUT",
                description: "출력 접점 12",
            },
            IoTemplate {
                suffix: "OUT13",
                bit: 29,
                direction: "OUT",
                description: "출력 접점 13",
            },
            IoTemplate {
                suffix: "OUT14",
                bit: 30,
                direction: "OUT",
                description: "출력 접점 14",
            },
            IoTemplate {
                suffix: "OUT15",
                bit: 31,
                direction: "OUT",
                description: "출력 접점 15",
            },
        ],
    },
    IoSpec {
        id: 42336,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
        ],
    },
    IoSpec {
        id: 42320,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "IN00",
                bit: 0,
                direction: "IN",
                description: "입력 접점 00",
            },
            IoTemplate {
                suffix: "IN01",
                bit: 1,
                direction: "IN",
                description: "입력 접점 01",
            },
            IoTemplate {
                suffix: "IN02",
                bit: 2,
                direction: "IN",
                description: "입력 접점 02",
            },
            IoTemplate {
                suffix: "IN03",
                bit: 3,
                direction: "IN",
                description: "입력 접점 03",
            },
            IoTemplate {
                suffix: "IN04",
                bit: 4,
                direction: "IN",
                description: "입력 접점 04",
            },
            IoTemplate {
                suffix: "IN05",
                bit: 5,
                direction: "IN",
                description: "입력 접점 05",
            },
        ],
    },
    IoSpec {
        id: 42252,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
        ],
    },
    IoSpec {
        id: 42253,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
            IoTemplate {
                suffix: "OUT08",
                bit: 8,
                direction: "OUT",
                description: "출력 접점 08",
            },
            IoTemplate {
                suffix: "OUT09",
                bit: 9,
                direction: "OUT",
                description: "출력 접점 09",
            },
            IoTemplate {
                suffix: "OUT10",
                bit: 10,
                direction: "OUT",
                description: "출력 접점 10",
            },
            IoTemplate {
                suffix: "OUT11",
                bit: 11,
                direction: "OUT",
                description: "출력 접점 11",
            },
            IoTemplate {
                suffix: "OUT12",
                bit: 12,
                direction: "OUT",
                description: "출력 접점 12",
            },
            IoTemplate {
                suffix: "OUT13",
                bit: 13,
                direction: "OUT",
                description: "출력 접점 13",
            },
            IoTemplate {
                suffix: "OUT14",
                bit: 14,
                direction: "OUT",
                description: "출력 접점 14",
            },
            IoTemplate {
                suffix: "OUT15",
                bit: 15,
                direction: "OUT",
                description: "출력 접점 15",
            },
        ],
    },
    IoSpec {
        id: 42284,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
        ],
    },
    IoSpec {
        id: 42285,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
            IoTemplate {
                suffix: "OUT08",
                bit: 8,
                direction: "OUT",
                description: "출력 접점 08",
            },
            IoTemplate {
                suffix: "OUT09",
                bit: 9,
                direction: "OUT",
                description: "출력 접점 09",
            },
            IoTemplate {
                suffix: "OUT10",
                bit: 10,
                direction: "OUT",
                description: "출력 접점 10",
            },
            IoTemplate {
                suffix: "OUT11",
                bit: 11,
                direction: "OUT",
                description: "출력 접점 11",
            },
            IoTemplate {
                suffix: "OUT12",
                bit: 12,
                direction: "OUT",
                description: "출력 접점 12",
            },
            IoTemplate {
                suffix: "OUT13",
                bit: 13,
                direction: "OUT",
                description: "출력 접점 13",
            },
            IoTemplate {
                suffix: "OUT14",
                bit: 14,
                direction: "OUT",
                description: "출력 접점 14",
            },
            IoTemplate {
                suffix: "OUT15",
                bit: 15,
                direction: "OUT",
                description: "출력 접점 15",
            },
        ],
    },
    IoSpec {
        id: 42286,
        points: 32,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
            IoTemplate {
                suffix: "OUT08",
                bit: 8,
                direction: "OUT",
                description: "출력 접점 08",
            },
            IoTemplate {
                suffix: "OUT09",
                bit: 9,
                direction: "OUT",
                description: "출력 접점 09",
            },
            IoTemplate {
                suffix: "OUT10",
                bit: 10,
                direction: "OUT",
                description: "출력 접점 10",
            },
            IoTemplate {
                suffix: "OUT11",
                bit: 11,
                direction: "OUT",
                description: "출력 접점 11",
            },
            IoTemplate {
                suffix: "OUT12",
                bit: 12,
                direction: "OUT",
                description: "출력 접점 12",
            },
            IoTemplate {
                suffix: "OUT13",
                bit: 13,
                direction: "OUT",
                description: "출력 접점 13",
            },
            IoTemplate {
                suffix: "OUT14",
                bit: 14,
                direction: "OUT",
                description: "출력 접점 14",
            },
            IoTemplate {
                suffix: "OUT15",
                bit: 15,
                direction: "OUT",
                description: "출력 접점 15",
            },
            IoTemplate {
                suffix: "OUT16",
                bit: 16,
                direction: "OUT",
                description: "출력 접점 16",
            },
            IoTemplate {
                suffix: "OUT17",
                bit: 17,
                direction: "OUT",
                description: "출력 접점 17",
            },
            IoTemplate {
                suffix: "OUT18",
                bit: 18,
                direction: "OUT",
                description: "출력 접점 18",
            },
            IoTemplate {
                suffix: "OUT19",
                bit: 19,
                direction: "OUT",
                description: "출력 접점 19",
            },
            IoTemplate {
                suffix: "OUT20",
                bit: 20,
                direction: "OUT",
                description: "출력 접점 20",
            },
            IoTemplate {
                suffix: "OUT21",
                bit: 21,
                direction: "OUT",
                description: "출력 접점 21",
            },
            IoTemplate {
                suffix: "OUT22",
                bit: 22,
                direction: "OUT",
                description: "출력 접점 22",
            },
            IoTemplate {
                suffix: "OUT23",
                bit: 23,
                direction: "OUT",
                description: "출력 접점 23",
            },
            IoTemplate {
                suffix: "OUT24",
                bit: 24,
                direction: "OUT",
                description: "출력 접점 24",
            },
            IoTemplate {
                suffix: "OUT25",
                bit: 25,
                direction: "OUT",
                description: "출력 접점 25",
            },
            IoTemplate {
                suffix: "OUT26",
                bit: 26,
                direction: "OUT",
                description: "출력 접점 26",
            },
            IoTemplate {
                suffix: "OUT27",
                bit: 27,
                direction: "OUT",
                description: "출력 접점 27",
            },
            IoTemplate {
                suffix: "OUT28",
                bit: 28,
                direction: "OUT",
                description: "출력 접점 28",
            },
            IoTemplate {
                suffix: "OUT29",
                bit: 29,
                direction: "OUT",
                description: "출력 접점 29",
            },
            IoTemplate {
                suffix: "OUT30",
                bit: 30,
                direction: "OUT",
                description: "출력 접점 30",
            },
            IoTemplate {
                suffix: "OUT31",
                bit: 31,
                direction: "OUT",
                description: "출력 접점 31",
            },
        ],
    },
    IoSpec {
        id: 42287,
        points: 64,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
            IoTemplate {
                suffix: "OUT08",
                bit: 8,
                direction: "OUT",
                description: "출력 접점 08",
            },
            IoTemplate {
                suffix: "OUT09",
                bit: 9,
                direction: "OUT",
                description: "출력 접점 09",
            },
            IoTemplate {
                suffix: "OUT10",
                bit: 10,
                direction: "OUT",
                description: "출력 접점 10",
            },
            IoTemplate {
                suffix: "OUT11",
                bit: 11,
                direction: "OUT",
                description: "출력 접점 11",
            },
            IoTemplate {
                suffix: "OUT12",
                bit: 12,
                direction: "OUT",
                description: "출력 접점 12",
            },
            IoTemplate {
                suffix: "OUT13",
                bit: 13,
                direction: "OUT",
                description: "출력 접점 13",
            },
            IoTemplate {
                suffix: "OUT14",
                bit: 14,
                direction: "OUT",
                description: "출력 접점 14",
            },
            IoTemplate {
                suffix: "OUT15",
                bit: 15,
                direction: "OUT",
                description: "출력 접점 15",
            },
            IoTemplate {
                suffix: "OUT16",
                bit: 16,
                direction: "OUT",
                description: "출력 접점 16",
            },
            IoTemplate {
                suffix: "OUT17",
                bit: 17,
                direction: "OUT",
                description: "출력 접점 17",
            },
            IoTemplate {
                suffix: "OUT18",
                bit: 18,
                direction: "OUT",
                description: "출력 접점 18",
            },
            IoTemplate {
                suffix: "OUT19",
                bit: 19,
                direction: "OUT",
                description: "출력 접점 19",
            },
            IoTemplate {
                suffix: "OUT20",
                bit: 20,
                direction: "OUT",
                description: "출력 접점 20",
            },
            IoTemplate {
                suffix: "OUT21",
                bit: 21,
                direction: "OUT",
                description: "출력 접점 21",
            },
            IoTemplate {
                suffix: "OUT22",
                bit: 22,
                direction: "OUT",
                description: "출력 접점 22",
            },
            IoTemplate {
                suffix: "OUT23",
                bit: 23,
                direction: "OUT",
                description: "출력 접점 23",
            },
            IoTemplate {
                suffix: "OUT24",
                bit: 24,
                direction: "OUT",
                description: "출력 접점 24",
            },
            IoTemplate {
                suffix: "OUT25",
                bit: 25,
                direction: "OUT",
                description: "출력 접점 25",
            },
            IoTemplate {
                suffix: "OUT26",
                bit: 26,
                direction: "OUT",
                description: "출력 접점 26",
            },
            IoTemplate {
                suffix: "OUT27",
                bit: 27,
                direction: "OUT",
                description: "출력 접점 27",
            },
            IoTemplate {
                suffix: "OUT28",
                bit: 28,
                direction: "OUT",
                description: "출력 접점 28",
            },
            IoTemplate {
                suffix: "OUT29",
                bit: 29,
                direction: "OUT",
                description: "출력 접점 29",
            },
            IoTemplate {
                suffix: "OUT30",
                bit: 30,
                direction: "OUT",
                description: "출력 접점 30",
            },
            IoTemplate {
                suffix: "OUT31",
                bit: 31,
                direction: "OUT",
                description: "출력 접점 31",
            },
            IoTemplate {
                suffix: "OUT32",
                bit: 32,
                direction: "OUT",
                description: "출력 접점 32",
            },
            IoTemplate {
                suffix: "OUT33",
                bit: 33,
                direction: "OUT",
                description: "출력 접점 33",
            },
            IoTemplate {
                suffix: "OUT34",
                bit: 34,
                direction: "OUT",
                description: "출력 접점 34",
            },
            IoTemplate {
                suffix: "OUT35",
                bit: 35,
                direction: "OUT",
                description: "출력 접점 35",
            },
            IoTemplate {
                suffix: "OUT36",
                bit: 36,
                direction: "OUT",
                description: "출력 접점 36",
            },
            IoTemplate {
                suffix: "OUT37",
                bit: 37,
                direction: "OUT",
                description: "출력 접점 37",
            },
            IoTemplate {
                suffix: "OUT38",
                bit: 38,
                direction: "OUT",
                description: "출력 접점 38",
            },
            IoTemplate {
                suffix: "OUT39",
                bit: 39,
                direction: "OUT",
                description: "출력 접점 39",
            },
            IoTemplate {
                suffix: "OUT40",
                bit: 40,
                direction: "OUT",
                description: "출력 접점 40",
            },
            IoTemplate {
                suffix: "OUT41",
                bit: 41,
                direction: "OUT",
                description: "출력 접점 41",
            },
            IoTemplate {
                suffix: "OUT42",
                bit: 42,
                direction: "OUT",
                description: "출력 접점 42",
            },
            IoTemplate {
                suffix: "OUT43",
                bit: 43,
                direction: "OUT",
                description: "출력 접점 43",
            },
            IoTemplate {
                suffix: "OUT44",
                bit: 44,
                direction: "OUT",
                description: "출력 접점 44",
            },
            IoTemplate {
                suffix: "OUT45",
                bit: 45,
                direction: "OUT",
                description: "출력 접점 45",
            },
            IoTemplate {
                suffix: "OUT46",
                bit: 46,
                direction: "OUT",
                description: "출력 접점 46",
            },
            IoTemplate {
                suffix: "OUT47",
                bit: 47,
                direction: "OUT",
                description: "출력 접점 47",
            },
            IoTemplate {
                suffix: "OUT48",
                bit: 48,
                direction: "OUT",
                description: "출력 접점 48",
            },
            IoTemplate {
                suffix: "OUT49",
                bit: 49,
                direction: "OUT",
                description: "출력 접점 49",
            },
            IoTemplate {
                suffix: "OUT50",
                bit: 50,
                direction: "OUT",
                description: "출력 접점 50",
            },
            IoTemplate {
                suffix: "OUT51",
                bit: 51,
                direction: "OUT",
                description: "출력 접점 51",
            },
            IoTemplate {
                suffix: "OUT52",
                bit: 52,
                direction: "OUT",
                description: "출력 접점 52",
            },
            IoTemplate {
                suffix: "OUT53",
                bit: 53,
                direction: "OUT",
                description: "출력 접점 53",
            },
            IoTemplate {
                suffix: "OUT54",
                bit: 54,
                direction: "OUT",
                description: "출력 접점 54",
            },
            IoTemplate {
                suffix: "OUT55",
                bit: 55,
                direction: "OUT",
                description: "출력 접점 55",
            },
            IoTemplate {
                suffix: "OUT56",
                bit: 56,
                direction: "OUT",
                description: "출력 접점 56",
            },
            IoTemplate {
                suffix: "OUT57",
                bit: 57,
                direction: "OUT",
                description: "출력 접점 57",
            },
            IoTemplate {
                suffix: "OUT58",
                bit: 58,
                direction: "OUT",
                description: "출력 접점 58",
            },
            IoTemplate {
                suffix: "OUT59",
                bit: 59,
                direction: "OUT",
                description: "출력 접점 59",
            },
            IoTemplate {
                suffix: "OUT60",
                bit: 60,
                direction: "OUT",
                description: "출력 접점 60",
            },
            IoTemplate {
                suffix: "OUT61",
                bit: 61,
                direction: "OUT",
                description: "출력 접점 61",
            },
            IoTemplate {
                suffix: "OUT62",
                bit: 62,
                direction: "OUT",
                description: "출력 접점 62",
            },
            IoTemplate {
                suffix: "OUT63",
                bit: 63,
                direction: "OUT",
                description: "출력 접점 63",
            },
        ],
    },
    IoSpec {
        id: 42269,
        points: 16,
        variables: &[
            IoTemplate {
                suffix: "OUT00",
                bit: 0,
                direction: "OUT",
                description: "출력 접점 00",
            },
            IoTemplate {
                suffix: "OUT01",
                bit: 1,
                direction: "OUT",
                description: "출력 접점 01",
            },
            IoTemplate {
                suffix: "OUT02",
                bit: 2,
                direction: "OUT",
                description: "출력 접점 02",
            },
            IoTemplate {
                suffix: "OUT03",
                bit: 3,
                direction: "OUT",
                description: "출력 접점 03",
            },
            IoTemplate {
                suffix: "OUT04",
                bit: 4,
                direction: "OUT",
                description: "출력 접점 04",
            },
            IoTemplate {
                suffix: "OUT05",
                bit: 5,
                direction: "OUT",
                description: "출력 접점 05",
            },
            IoTemplate {
                suffix: "OUT06",
                bit: 6,
                direction: "OUT",
                description: "출력 접점 06",
            },
            IoTemplate {
                suffix: "OUT07",
                bit: 7,
                direction: "OUT",
                description: "출력 접점 07",
            },
            IoTemplate {
                suffix: "OUT08",
                bit: 8,
                direction: "OUT",
                description: "출력 접점 08",
            },
            IoTemplate {
                suffix: "OUT09",
                bit: 9,
                direction: "OUT",
                description: "출력 접점 09",
            },
            IoTemplate {
                suffix: "OUT10",
                bit: 10,
                direction: "OUT",
                description: "출력 접점 10",
            },
            IoTemplate {
                suffix: "OUT11",
                bit: 11,
                direction: "OUT",
                description: "출력 접점 11",
            },
            IoTemplate {
                suffix: "OUT12",
                bit: 12,
                direction: "OUT",
                description: "출력 접점 12",
            },
            IoTemplate {
                suffix: "OUT13",
                bit: 13,
                direction: "OUT",
                description: "출력 접점 13",
            },
            IoTemplate {
                suffix: "OUT14",
                bit: 14,
                direction: "OUT",
                description: "출력 접점 14",
            },
            IoTemplate {
                suffix: "OUT15",
                bit: 15,
                direction: "OUT",
                description: "출력 접점 15",
            },
        ],
    },
    IoSpec {
        id: 42362,
        points: 32,
        variables: &[
            IoTemplate {
                suffix: "CH0_LINE_DIAG",
                bit: 8,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 0 단선 진단",
            },
            IoTemplate {
                suffix: "CH0_OUT",
                bit: 16,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 0",
            },
            IoTemplate {
                suffix: "CH0_SIG_DIAG",
                bit: 0,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 0 진단",
            },
            IoTemplate {
                suffix: "CH1_LINE_DIAG",
                bit: 9,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 1 단선 진단",
            },
            IoTemplate {
                suffix: "CH1_OUT",
                bit: 17,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 1",
            },
            IoTemplate {
                suffix: "CH1_SIG_DIAG",
                bit: 1,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 1 진단",
            },
            IoTemplate {
                suffix: "CH2_LINE_DIAG",
                bit: 10,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 2 단선 진단",
            },
            IoTemplate {
                suffix: "CH2_OUT",
                bit: 18,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 2",
            },
            IoTemplate {
                suffix: "CH2_SIG_DIAG",
                bit: 2,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 2 진단",
            },
            IoTemplate {
                suffix: "CH3_LINE_DIAG",
                bit: 11,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 3 단선 진단",
            },
            IoTemplate {
                suffix: "CH3_OUT",
                bit: 19,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 3",
            },
            IoTemplate {
                suffix: "CH3_SIG_DIAG",
                bit: 3,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 3 진단",
            },
            IoTemplate {
                suffix: "CH4_LINE_DIAG",
                bit: 12,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 4 단선 진단",
            },
            IoTemplate {
                suffix: "CH4_OUT",
                bit: 20,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 4",
            },
            IoTemplate {
                suffix: "CH4_SIG_DIAG",
                bit: 4,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 4 진단",
            },
            IoTemplate {
                suffix: "CH5_LINE_DIAG",
                bit: 13,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 5 단선 진단",
            },
            IoTemplate {
                suffix: "CH5_OUT",
                bit: 21,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 5",
            },
            IoTemplate {
                suffix: "CH5_SIG_DIAG",
                bit: 5,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 5 진단",
            },
            IoTemplate {
                suffix: "CH6_LINE_DIAG",
                bit: 14,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 6 단선 진단",
            },
            IoTemplate {
                suffix: "CH6_OUT",
                bit: 22,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 6",
            },
            IoTemplate {
                suffix: "CH6_SIG_DIAG",
                bit: 6,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 6 진단",
            },
            IoTemplate {
                suffix: "CH7_LINE_DIAG",
                bit: 15,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 출력 7 단선 진단",
            },
            IoTemplate {
                suffix: "CH7_OUT",
                bit: 23,
                direction: "OUT",
                description: "진단형 릴레이 출력모듈: 릴레이 출력 7",
            },
            IoTemplate {
                suffix: "CH7_SIG_DIAG",
                bit: 7,
                direction: "IN",
                description: "진단형 릴레이 출력모듈: 내부 출력신호 7 진단",
            },
        ],
    },
];
